using System.Collections.Generic;
using System.Text;
using Bpf.Markup.Generator.Model;

namespace Bpf.Markup.Generator.Emitter
{
    /// <summary>
    /// BpfamlDocument → C# 源代码字符串。
    /// 发射一个 partial class,提供 Build() 工厂方法返回根控件实例。
    ///
    /// 设计:bpf 控件多为 sealed 无法继承,故生成的类不继承控件,而是作为工厂。
    ///   x:Class="App.MainForm" + &lt;StackPanel&gt; →
    ///     public partial class MainForm {
    ///         public static StackPanel Build() { ... new StackPanel() ... return root; }
    ///     }
    ///   用户:var form = MainForm.Build(); window.SetContent(form);
    ///
    /// 生成的类持有:
    ///   - x:Name 元素 → private static 字段(通过 Fields 访问器暴露,阶段 A 暂用静态)
    ///   - Build() 方法:实例化根 + 子树,返回根
    /// 后续阶段加:属性转换器(Color/Brush/enum/GridLength)、附加属性、事件、绑定、资源、Style。
    /// </summary>
    internal sealed class BpfamlEmitter
    {
        private readonly StringBuilder _sb = new StringBuilder();
        private int _indent;
        private int _varCounter;

        /// <summary>发射整个文档。返回 (hintName, sourceText)。</summary>
        public (string hintName, string source) Emit(BpfamlDocument doc)
        {
            int lastDot = doc.ClassFullName.LastIndexOf('.');
            string ns = lastDot > 0 ? doc.ClassFullName.Substring(0, lastDot) : "";
            string className = lastDot > 0 ? doc.ClassFullName.Substring(lastDot + 1) : doc.ClassFullName;
            string rootType = doc.Root.FullTypeName;
            _classNameForStatic = className;
            _dataTypeFullName = doc.DataTypeFullName;

            _sb.Clear();
            _indent = 0;
            _varCounter = 0;

            Line("// <auto-generated/>");
            Line("#pragma warning disable");
            Line("#nullable enable");
            Line("");

            if (ns.Length > 0) { Line($"namespace {ns}"); Line("{"); _indent++; }

            // partial class(普通类,不继承控件 —— 控件多为 sealed)
            Line($"public partial class {className}");
            Line("{");
            _indent++;

            // x:Name → private static 字段(Build 时赋值,code-behind 通过 MainForm.myBtn 访问)
            // 阶段 A:static 简化;阶段 C 起若需多实例支持再改为实例字段 + 访问器
            foreach (var (name, type) in doc.NamedElements)
                Line($"internal static global::{type}? {name};");
            if (doc.NamedElements.Count > 0) Line("");

            // Build() 工厂方法
            Line($"public static global::{rootType} Build()");
            Line("{");
            _indent++;

            // 阶段 E:先发射编译期资源(根元素的 <X.Resources>),作为局部变量。
            // {StaticResource Key} 直接引用这些局部变量(零运行时查找,AOT 最佳)。
            // 根元素的 EmitChildren 会把它们加入 root.Resources[key] = var。
            ScanAndEmitRootResources(doc.Root);

            // 根元素实例化(根也可能是 x:Name,但通常根不命名)
            string rootVar = EmitElement(doc.Root);
            Line($"return {rootVar};");

            _indent--;
            Line("}");
            _indent--;

            _indent--;
            Line("}");
            if (ns.Length > 0) { _indent--; Line("}"); }

            string hintName = $"{className}.g.cs";
            return (hintName, _sb.ToString());
        }

        /// <summary>
        /// 发射一个元素的实例化,返回它的变量名(或静态字段引用)。
        /// 递归处理它的属性和子元素。根元素和子元素都走此方法。
        /// </summary>
        private string EmitElement(BpfamlElement element)
        {
            string xName = GetXName(element);
            string varName;
            if (xName != null)
            {
                // 静态字段(类名.字段名),code-behind 通过 MainForm.myBtn 访问
                Line($"{_classNameForStatic}.{xName} = new global::{element.FullTypeName}();");
                varName = $"{_classNameForStatic}.{xName}";
            }
            else
            {
                varName = NextVar(element.LocalName);
                Line($"var {varName} = new global::{element.FullTypeName}();");
            }

            EmitAttributes(varName, element);
            EmitChildren(varName, element);
            return varName;
        }

        // 当前生成的类名(用于静态字段引用 MainForm.myBtn)
        // 在 Emit 开头设置
        private string _classNameForStatic = "";

        // x:DataType 的全限定名(空 = 未声明,{Binding} 会发诊断或退化)
        private string _dataTypeFullName = "";

        // 编译期资源表:扫描根元素的 <X.Resources> 收集的 key → C# 表达式。
        // {StaticResource Key} 在普通属性里直接替换为对应表达式(零运行时查找,AOT 最佳)。
        private readonly Dictionary<string, string> _rootResources = new Dictionary<string, string>();

        /// <summary>发射元素的所有非 x:Name 属性。__textContent 单独处理。</summary>
        private void EmitAttributes(string varName, BpfamlElement element)
        {
            foreach (var attr in element.Attributes)
            {
                string name = attr.Name;
                if (name == "x:Name" || name == "Name") continue;
                if (name == "__textContent") continue;

                // 附加属性(含点号,如 Grid.Column)→ 调用静态 Set 方法
                int dot = name.IndexOf('.');
                if (dot > 0)
                {
                    EmitAttachedProperty(varName, name, attr.Value);
                    continue;
                }

                // markup extension({Binding}/{StaticResource}/...)
                if (attr.IsMarkupExtension)
                {
                    EmitMarkupExtension(varName, element, name, attr.Value);
                    continue;
                }

                // 事件名(Click/SelectionChanged/...)→ += MainForm.OnClick
                // 值 = 用户在 code-behind 写的处理方法名(静态)
                if (KnownEvents.IsEvent(name))
                {
                    Line($"{varName}.{name} += {_classNameForStatic}.{attr.Value};");
                    continue;
                }

                // 普通属性:按类型转换器发射赋值表达式
                string? expr = ConvertValue(name, attr.Value);
                if (expr != null)
                    Line($"{varName}.{name} = {expr};");
                // Unknown 类型:静默忽略(阶段 B 容错)。后续可发诊断。
            }
        }

        /// <summary>发射附加属性:Grid.Column="1" → Grid.SetColumn(target, 1)。</summary>
        private void EmitAttachedProperty(string target, string fullName, string value)
        {
            int dot = fullName.IndexOf('.');
            string owner = fullName.Substring(0, dot);
            string prop = fullName.Substring(dot + 1);

            // 已知附加属性表(owner + prop → Set 方法 + 值类型)
            // bpf 目前只有 Grid 的四个附加属性。
            string? ownerFull = owner switch
            {
                "Grid" => "Bpf.Controls.Grid",
                _ => null,
            };
            if (ownerFull == null) return; // 未知属主,忽略

            string? setterName = (owner, prop) switch
            {
                ("Grid", "Row") => "SetRow",
                ("Grid", "Column") => "SetColumn",
                ("Grid", "RowSpan") => "SetRowSpan",
                ("Grid", "ColumnSpan") => "SetColumnSpan",
                _ => null,
            };
            if (setterName == null) return;

            // Grid 的附加属性都是 int
            string? expr = ConvertInt(value);
            if (expr != null)
                Line($"global::{ownerFull}.{setterName}({target}, {expr});");
        }

        /// <summary>
        /// 把字符串值转成 C# 表达式(已求值)。返回 null 表示无法转换(跳过)。
        /// 阶段 B:覆盖所有已知属性类型。
        /// </summary>
        private string? ConvertValue(string propName, string value)
        {
            switch (PropertyTypes.Get(propName))
            {
                case PropType.String:
                    return Quote(value);
                case PropType.Double:
                    return ConvertDouble(value);
                case PropType.Int:
                    return ConvertInt(value);
                case PropType.Bool:
                    return ConvertBool(value);
                case PropType.Brush:
                    // new SolidColorBrush(Color.Parse("..."))
                    return $"new global::Bpf.Media.SolidColorBrush(global::Bpf.Media.Color.Parse({Quote(value)}))";
                case PropType.Color:
                    return $"global::Bpf.Media.Color.Parse({Quote(value)})";
                case PropType.Stretch:
                    return $"global::Bpf.Media.Stretch.{Cap(value)}";
                case PropType.Orientation:
                    return $"global::Bpf.Controls.Orientation.{Cap(value)}";
                case PropType.FontWeight:
                    // FontWeight 是数值枚举(Normal=400, Bold=700...)。优先按名,再按数字。
                    if (int.TryParse(value.Trim(), out _))
                        return $"(global::Bpf.Platform.FontWeight){ConvertInt(value)}";
                    return $"(global::Bpf.Platform.FontWeight)global::System.Enum.Parse(typeof(global::Bpf.Platform.FontWeight), {Quote(Cap(value))})";
                case PropType.FontStyle:
                    return $"(global::Bpf.Platform.FontStyle)global::System.Enum.Parse(typeof(global::Bpf.Platform.FontStyle), {Quote(Cap(value))})";
                case PropType.GridLengthString:
                    return Quote(value);
                default:
                    return null;
            }
        }

        // ── markup extension({Binding}/{StaticResource}/{x:Static}/{x:Null}) ──

        private void EmitMarkupExtension(string varName, BpfamlElement element, string propName, string value)
        {
            // 去掉外层 { }
            string inner = value.Trim();
            if (inner.StartsWith("{")) inner = inner.Substring(1);
            if (inner.EndsWith("}")) inner = inner.Substring(0, inner.Length - 1);
            inner = inner.Trim();

            var ext = MarkupExtension.Parse(inner);
            switch (ext.Name)
            {
                case "Binding":
                    EmitBinding(varName, element, propName, ext);
                    break;
                case "x:Null":
                    // 在属性赋值上下文:把属性设为 null。需知道属性名,这里无法直接赋值,
                    // 用专用标记 —— 阶段 E 简化:仅在 Style.Setter 里支持(ResolveMarkupValue)。
                    // 普通属性赋值的 {x:Null} 走 ResolveMarkupValue 间接,此处忽略。
                    break;
                case "x:Static":
                case "StaticResource":
                    {
                        // 把 markup extension 解析成值表达式,直接赋给属性
                        string? expr = ResolveMarkupValue(value);
                        if (expr != null)
                            Line($"{varName}.{propName} = {expr};");
                        break;
                    }
            }
        }

        /// <summary>
        /// 发射 {Binding Path} → CompiledBinding + SetCompiledBinding 调用。
        /// 生成强类型 lambda:vm =&gt; vm.Path(get)+ (vm, v) =&gt; vm.Path = v(set,TwoWay)。
        /// 要求 x:DataType 已声明,否则跳过(后续可发诊断 BPFAML0003)。
        /// </summary>
        private void EmitBinding(string varName, BpfamlElement element, string propName, MarkupExtension ext)
        {
            if (_dataTypeFullName.Length == 0)
            {
                // 无 DataType:阶段 D 不支持无类型绑定,跳过。
                return;
            }

            // Path:第一个位置参数,或 NamedArgs["Path"]
            string path;
            if (ext.PositionalArgs.Count > 0) path = ext.PositionalArgs[0];
            else if (ext.NamedArgs.TryGetValue("Path", out var p)) path = p;
            else path = ""; // 无 Path = 绑定到 DataContext 本身

            // Mode
            string modeStr = ext.NamedArgs.TryGetValue("Mode", out var m) ? m : "OneWay";
            string modeEnum = modeStr switch
            {
                "TwoWay" => "global::Bpf.Data.BindingMode.TwoWay",
                "OneTime" => "global::Bpf.Data.BindingMode.OneTime",
                _ => "global::Bpf.Data.BindingMode.OneWay",
            };

            // 属性的 StyledProperty 字段全名
            string? fieldFullName = PropertyFields.Find(element.FullTypeName, propName);
            if (fieldFullName == null)
            {
                // 属性不是已知 StyledProperty(可能是 CLR 属性如 SelectedIndex),绑定跳过
                return;
            }

            // 生成 lambda 体内的属性访问链:path "A.B.C" → vm.A.B.C
            string access = BuildPathAccess(path);
            // 观察的属性名(路径最后一段,用于 INPC 订阅)。也观察中间段。
            var observed = BuildObservedNames(path);

            // get lambda:object? → object?。强类型转换:((DataType)src).A.B.C
            string dt = _dataTypeFullName;
            string getLambda = path.Length == 0
                ? "(object? src) => src"
                : $"(object? src) => {{ {dt}? __t = src as {dt}; return __t is null ? null : (object?){Box(access)}; }}";

            // set lambda(TwoWay 才生成)。M6 阶段 D:TwoWay 的自动回写需要属性类型信息,
            // 发射器目前不带类型表,故 TwoWay 暂只生成 get(单向刷新),不自动回写源。
            // 用户若需双向,可用 code-behind 事件手工回写(见 sample)。后续阶段加类型推断后支持。
            string setLambda = "null";

            // 观察名数组
            string observedArray = observed.Count == 0
                ? "global::System.Array.Empty<string>()"
                : "new string[] { " + JoinQuoted(observed) + " }";

            Line($"{varName}.SetCompiledBinding({fieldFullName}, new global::Bpf.Data.CompiledBinding({getLambda}, {setLambda}, {modeEnum}, {observedArray}));");
        }

        /// <summary>构造路径访问表达式:输入 "A.B.C",输出 "__t.A.B.C"(已加 __t 前缀)。</summary>
        private static string BuildPathAccess(string path)
        {
            if (path.Length == 0) return "__t";
            return "__t." + path;
        }

        /// <summary>路径 → 观察的属性名列表(每一段都是一个可观察属性)。</summary>
        private static List<string> BuildObservedNames(string path)
        {
            var result = new List<string>();
            if (path.Length == 0) return result;
            foreach (var seg in path.Split('.'))
            {
                var s = seg.Trim();
                if (s.Length > 0) result.Add(s);
            }
            return result;
        }

        // 注:TwoWay set lambda 留后续阶段(需属性类型表推断目标属性类型)。

        /// <summary>把访问表达式包成 object?(值类型装箱)。</summary>
        private static string Box(string access) =>
            access;  // 已是属性访问,返回 object? 时 C# 自动装箱;nullable 引用类型直接返

        private static string JoinQuoted(List<string> xs)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < xs.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append('"').Append(xs[i]).Append('"');
            }
            return sb.ToString();
        }

        // ── 原始类型转换(失败返回 null,生成器跳过该属性 + 发诊断) ──

        private static string? ConvertDouble(string s) =>
            double.TryParse(s.Trim(), System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out var v)
                ? v.ToString(System.Globalization.CultureInfo.InvariantCulture)
                : (string?)null;

        private static string? ConvertInt(string s) =>
            int.TryParse(s.Trim(), out var v) ? v.ToString() : (string?)null;

        private static string? ConvertBool(string s)
        {
            string t = s.Trim().ToLowerInvariant();
            if (t == "true" || t == "1") return "true";
            if (t == "false" || t == "0") return "false";
            return null;
        }

        /// <summary>首字母大写(枚举成员名规范化:Horizontal → Horizontal)。</summary>
        private static string Cap(string s)
        {
            if (s.Length == 0) return s;
            // 接受 "horizontal"(小写)→ "Horizontal"
            var sb = new StringBuilder(s.Length);
            sb.Append(char.ToUpperInvariant(s[0]));
            for (int i = 1; i < s.Length; i++) sb.Append(s[i]);
            return sb.ToString();
        }

        /// <summary>
        /// 扫描根元素的 &lt;Owner.Resources&gt; 属性元素,把每个带 x:Key 的资源作为局部变量发射,
        /// 并登记到 _rootResources(key → 变量名)。后续 EmitPropertyElement(Resources) 引用这些变量,
        /// {StaticResource Key} 也直接引用(编译期解析,零运行时查找)。
        /// </summary>
        private void ScanAndEmitRootResources(BpfamlElement root)
        {
            foreach (var node in root.Children)
            {
                if (node is BpfamlPropertyElementNode pe && pe.PropertyName == "Resources")
                {
                    // Resources 的所有子元素(ValueElement 首个 + CollectionItems 后续)都是资源
                    var items = new List<BpfamlElement>();
                    if (pe.ValueElement != null) items.Add(pe.ValueElement);
                    items.AddRange(pe.CollectionItems);
                    foreach (var item in items)
                    {
                        string? key = GetXKey(item);
                        if (key == null) continue;
                        // 保存属性副本(含 x:Key),发射时临时去掉 x:Key(它不是真实属性),发射后恢复
                        var prevAttrs = new List<BpfamlAttribute>(item.Attributes);
                        var filtered = new List<BpfamlAttribute>();
                        foreach (var a in prevAttrs)
                            if (a.Name != "x:Key" && a.Name != "Key") filtered.Add(a);
                        ReplaceAttributes(item, filtered);
                        string itemVar = EmitElement(item);
                        RestoreAttributes(item, prevAttrs);
                        _rootResources[key] = itemVar;
                    }
                }
            }
        }

        // 临时替换/恢复元素属性(扫描资源时去掉 x:Key)。避免在 BpfamlElement 加可变状态污染模型。
        private static void ReplaceAttributes(BpfamlElement e, List<BpfamlAttribute> newAttrs)
        {
            e.Attributes.Clear();
            e.Attributes.AddRange(newAttrs);
        }
        private static void RestoreAttributes(BpfamlElement e, List<BpfamlAttribute> oldAttrs)
        {
            e.Attributes.Clear();
            e.Attributes.AddRange(oldAttrs);
        }

        /// <summary>发射元素的子节点(子元素、文本内容)。属性元素留阶段 B。</summary>
        private void EmitChildren(string varName, BpfamlElement element)
        {
            var strategy = ContentStrategies.Get(element.FullTypeName);

            var textAttr = FindAttr(element.Attributes, "__textContent");
            if (textAttr != null && strategy == ContentStrategy.ContentString)
                Line($"{varName}.Content = {Quote(textAttr.Value)};");
            else if (textAttr != null && strategy == ContentStrategy.TextString)
                Line($"{varName}.Text = {Quote(textAttr.Value)};");

            foreach (var node in element.Children)
            {
                if (node is BpfamlElementNode elemNode)
                {
                    var childElement = elemNode.Element;
                    // Style 作为直接子元素(常出现在 <X.Styles> 或 <X.Resources> 内;也支持作为
                    // 面板的直接子元素自动加入 Styles,但通常应放在 <X.Styles>)。
                    if (childElement.LocalName == "Style")
                    {
                        var styleExpr = BuildStyle(childElement);
                        if (styleExpr != null)
                            Line($"{varName}.Styles.Add({styleExpr});");
                        continue;
                    }
                    var childVar = EmitElement(childElement);
                    switch (strategy)
                    {
                        case ContentStrategy.PanelAddChild:
                            Line($"{varName}.AddChild({childVar});");
                            break;
                        case ContentStrategy.ChildSingle:
                            Line($"{varName}.Child = {childVar};");
                            break;
                            // None / ContentString / TextString 的子元素忽略(阶段 A 容错)
                    }
                }
                else if (node is BpfamlPropertyElementNode propNode)
                {
                    EmitPropertyElement(varName, element, propNode);
                }
            }
        }

        /// <summary>处理属性元素 &lt;Owner.Property&gt;:Resources / Styles / DataContext / 复杂属性。</summary>
        private void EmitPropertyElement(string parentVar, BpfamlElement parent, BpfamlPropertyElementNode propNode)
        {
            string prop = propNode.PropertyName;

            switch (prop)
            {
                case "Resources":
                    {
                        var items = new List<BpfamlElement>();
                        if (propNode.ValueElement != null) items.Add(propNode.ValueElement);
                        items.AddRange(propNode.CollectionItems);
                        foreach (var item in items)
                        {
                            string? key = GetXKey(item);
                            if (key == null) continue;
                            if (_rootResources.TryGetValue(key, out var varRef))
                                Line($"{parentVar}.Resources[{Quote(key)}] = {varRef};");
                        }
                    }
                    break;

                case "Styles":
                    {
                        // Style 可能在 ValueElement(单个)或 CollectionItems(多个)
                        var items = new List<BpfamlElement>();
                        if (propNode.ValueElement != null) items.Add(propNode.ValueElement);
                        items.AddRange(propNode.CollectionItems);
                        foreach (var item in items)
                        {
                            if (item.LocalName != "Style") continue;
                            var styleExpr = BuildStyle(item);
                            if (styleExpr != null)
                                Line($"{parentVar}.Styles.Add({styleExpr});");
                        }
                    }
                    break;

                case "DataContext":
                    if (propNode.ValueElement != null)
                    {
                        string dcVar = EmitElement(propNode.ValueElement);
                        Line($"{parentVar}.DataContext = {dcVar};");
                    }
                    break;

                default:
                    // 通用复杂属性:Owner.Background = <SolidColorBrush/>
                    if (propNode.ValueElement != null)
                    {
                        string valVar = EmitElement(propNode.ValueElement);
                        Line($"{parentVar}.{prop} = {valVar};");
                    }
                    break;
            }
        }

        /// <summary>从 Style 元素构造表达式:new Style&lt;T&gt;().Add(prop, val).Add(...)。</summary>
        private string? BuildStyle(BpfamlElement styleElement)
        {
            // TargetType="TextBlock" → 解析为全名,取泛型参数
            string? targetLocal = null;
            foreach (var a in styleElement.Attributes)
            {
                if (a.Name == "TargetType") { targetLocal = a.Value; break; }
            }
            if (targetLocal == null || !KnownTypes.TryResolve(targetLocal, out var targetFull))
                return null;

            // 构造:new global::Bpf.Styling.Style<T>().Add(...).Add(...)
            var sb = new StringBuilder();
            sb.Append($"new global::Bpf.Styling.Style<{targetFull}>()");
            // 每个 <Setter Property="..." Value="..."/> 子元素 → .Add(XxxProperty, value)
            foreach (var node in styleElement.Children)
            {
                if (node is BpfamlElementNode en && en.Element.LocalName == "Setter")
                {
                    var setter = en.Element;
                    string? sProp = null, sValue = null;
                    foreach (var a in setter.Attributes)
                    {
                        if (a.Name == "Property") sProp = a.Value;
                        else if (a.Name == "Value") sValue = a.Value;
                    }
                    if (sProp == null || sValue == null) continue;

                    string? fieldFull = PropertyFields.Find(targetFull, sProp);
                    if (fieldFull == null) continue;

                    // Value 转换:优先识别 markup extension({StaticResource}/{x:Static}/{x:Null}),
                    // 否则按属性类型转换
                    string? valueExpr = null;
                    if (sValue.Length > 0 && sValue.TrimStart()[0] == '{')
                        valueExpr = ResolveMarkupValue(sValue);
                    if (valueExpr == null)
                        valueExpr = ConvertValue(sProp, sValue);
                    if (valueExpr == null) continue;

                    sb.Append($".Add({fieldFull}, {valueExpr})");
                }
            }
            return sb.ToString();
        }

        /// <summary>{StaticResource Key} → 在生成代码里用 this/根的资源查找;{x:Static M.X} → global::M.X;{x:Null} → null。</summary>
        private string? ResolveMarkupValue(string value)
        {
            string inner = value.Trim();
            if (inner.StartsWith("{")) inner = inner.Substring(1);
            if (inner.EndsWith("}")) inner = inner.Substring(0, inner.Length - 1);
            inner = inner.Trim();
            var ext = MarkupExtension.Parse(inner);
            switch (ext.Name)
            {
                case "StaticResource":
                    // key 是第一个位置参数
                    string key = ext.PositionalArgs.Count > 0 ? ext.PositionalArgs[0] : "";
                    // 阶段 E:运行时查找(沿树)。生成 code: (T)rootVar.FindResource("key")
                    // 但此处没有 rootVar 上下文(在 Build() 内变量名不稳定)。
                    // 简化:把资源查找做成延迟 —— 用一个生成的辅助方法 ResolveResource。
                    // M6 阶段 E:{StaticResource} 在 Style.Setter 里暂用运行时查找,需要控件引用。
                    // 折中:生成 (global::Bpf.Media.Brush)global::Bpf.Markup.Runtime.BpfamlResources.Find(this, key)
                    // 但 Style 在构造时没有控件实例。
                    // 最简方案:要求资源必须在同一 .bpfaml 的根 Resources 里,发射期已知值 → 直接内联。
                    // 这里用编译期资源表(_resources 字段,见 Emit 末尾)。
                    if (_rootResources.TryGetValue(key, out var resExpr))
                        return resExpr;
                    return null;
                case "x:Static":
                    // {x:Static Namespace.Type.Member} → global::Namespace.Type.Member
                    if (ext.PositionalArgs.Count > 0)
                        return ResolveStaticMember(ext.PositionalArgs[0]);
                    return null;
                case "x:Null":
                    return "null";
            }
            return null;
        }

        /// <summary>解析 "Stretch.Uniform" 或 "Bpf.Media.Stretch.Uniform" → global::... 全限定成员。</summary>
        private static string ResolveStaticMember(string member)
        {
            // 若已含命名空间点,直接 global:: 化
            if (member.Contains("."))
                return "global::" + member;
            return member;
        }

        /// <summary>读取元素的 x:Key 属性(资源键)。</summary>
        private static string? GetXKey(BpfamlElement e)
        {
            foreach (var a in e.Attributes)
                if (a.Name == "x:Key" || a.Name == "Key") return a.Value;
            return null;
        }

        // ── 辅助 ──

        private string NextVar(string localName)
        {
            _varCounter++;
            return LowerFirst(localName) + _varCounter;
        }

        private static string LowerFirst(string s) =>
            s.Length == 0 ? "element" : char.ToLowerInvariant(s[0]) + s.Substring(1);

        private static string? GetXName(BpfamlElement element)
        {
            for (int i = 0; i < element.Attributes.Count; i++)
            {
                var a = element.Attributes[i];
                if (a.Name == "x:Name" || a.Name == "Name") return a.Value!;
            }
            return null;
        }

        private static BpfamlAttribute? FindAttr(List<BpfamlAttribute> attrs, string name)
        {
            for (int i = 0; i < attrs.Count; i++)
                if (attrs[i].Name == name) return attrs[i];
            return null;
        }

        private static string Quote(string s)
        {
            if (s == null) return "\"\"";
            var sb = new StringBuilder(s.Length + 2);
            sb.Append('"');
            foreach (char c in s)
            {
                switch (c)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '"': sb.Append("\\\""); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default: sb.Append(c); break;
                }
            }
            sb.Append('"');
            return sb.ToString();
        }

        private void Line(string s = "")
        {
            for (int i = 0; i < _indent; i++) _sb.Append("    ");
            _sb.AppendLine(s);
        }
    }
}
